name: json

on:
  push:
    paths:
      - "**.json"
  pull_request:
    paths:
      - "**.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check JSON syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
